# This yml file is used primary for default configurations settings (fallback when parameters set in parameters.yml are invalid) and data schema related settings involving the key data features name which are used for processing related activities. They should only be changed in circumstances where data values or feature names has changed.


####### Data loader defaults
default_date_col: "Date" #Assume date col name for all input dataset
default_propensity_factor_column: "Factor"
default_mkt_channels_column: "Mode"
default_mkt_cost_column: "Total Cost"
default_mkt_name_column: "Name"
default_mkt_date_start_end_columns: ["Date Start", "Date End"]
default_outlet_column: "CostCentreCode"
default_columns_to_construct_date:
    weather_data: ["Year", "Month", "Day"]
    marketing_data: ["Date Start", "Date End"]
# ----------------------------------------------------------------------
####### Used for data preprocessing
default_start_date: "2021-01-01" 
default_end_date: "2022-12-31"
# Target column (lowercase due to dataloader column renaming)
default_revenue_column: "proxyrevenue"
default_const_value_perc_threshold: 0
default_outlets_exclusion_list: []

# ----------------------------------------------------------------------
####### Data Split default configurations for train/val/test days in case of misconfiguration
data_split:
    training_days_default: 365
    validation_days_default: 14
    testing_days_default: 14
    window_sliding_stride_days_default: 90
    window_expansion_days_default: 90
    simple_split_fold_default: 1 # Defaults if simple_split chosen but invalid fold stated
    window_split_fold_default: 3 # Defaults if sliding/expanding_window chosen but invalid fold stated
    data_split_option_list: ["simple_split", "expanding_window", "sliding_window"]
    data_split_option_default: "simple_split" #Fallback defaults

# ----------------------------------------------------------------------
####### Model training default configurations in case of misconfiguration
modeling:
    valid_model_name_list: ["ebm", "ordered_model"]
    default_model: "ebm"
    ebm:
        outer_bags: 10
        inner_bags:  0
        learning_rate: 0.01
        interactions: 0
        max_leaves: 3
        max_bins: 256
        min_samples_leaf: 2

    ordered_model:
        distr: "probit"
        method: "bfgs"
        max_iter: 2

    explainability_filepath: "models/ebm_explanation/"

# ----------------------------------------------------------------------
###### Defaults used for inference pipeline
inference:
    lag_sales_filename: "inference_lag_sales_data"
    marketing_filename: "inference_mkt_data"
    outlet_filename: "inference_outlet_data"
    marketing_filepath: "data/08_model_inference_output/inference_mkt_data/inference_mkt_data.csv"
    lag_sales_filepath: "data/08_model_inference_output/inference_lag_sales_data/inference_lag_sales_data.csv"
    outlet_filepath: "data/08_model_inference_output/inference_outlet_data/inference_outlet_data.csv"
    lag_sales_partition_filepath: "data/08_model_inference_output/inference_lag_sales_data"
    # artefacts 
    tsfresh_relevant_features_filepath: "data/05_feature_engineering/tsfresh_features/artefacts/tsfresh_relevant_features"
    std_norm_filepath: "data/08_model_inference_output/std_norm_artefact"
    encoding_filepath: "data/08_model_inference_output/encoding_artefact"
    ebm_explain_filepath: "data/08_model_inference_output/ebm_explanation"
