# This is a boilerplate parameters config generated for pipeline 'data_split'
# using Kedro 0.18.10.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.10/kedro_project_setup/configuration.html#parameters
outlet_name: ["AZ","Z"]

data_split:
    time_index_split: 
        train:
            value: 60
        val:
            value: 20

